@safetestset "First Order Methods" include("rootfind_tests__item1.jl")
@safetestset "Second Order Methods" include("rootfind_tests__item2.jl")
@safetestset "Derivative Free Methods" include("rootfind_tests__item3.jl")
@safetestset "Newton Fails" include("rootfind_tests__item4.jl")
@safetestset "Kwargs Propagation" include("rootfind_tests__item5.jl")
