@safetestset "Broyden" include("core_tests__item1.jl")
@safetestset "Broyden: Iterator Interface" include("core_tests__item2.jl")
@safetestset "Broyden Termination Conditions" include("core_tests__item3.jl")
@safetestset "Klement" include("core_tests__item4.jl")
@safetestset "Klement: Iterator Interface" include("core_tests__item5.jl")
@safetestset "Klement Termination Conditions" include("core_tests__item6.jl")
@safetestset "LimitedMemoryBroyden" include("core_tests__item7.jl")
@safetestset "LimitedMemoryBroyden: Iterator Interface" include("core_tests__item8.jl")
@safetestset "LimitedMemoryBroyden Termination Conditions" include("core_tests__item9.jl")
