style = "yas"
indent = 4
margin = 100
always_for_in = true
whitespace_ops_in_indices = true
whitespace_typedefs = false
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = false
short_to_long_function_def = false
always_use_return = true
whitespace_in_kwargs = true