@safetestset "Manual SCC" include("core_tests__item1.jl")
@safetestset "SCCNonlinearProblem solve without explicit u0 (issue #758)" include("core_tests__item2.jl")
@safetestset "SCC Residuals Transfer" include("core_tests__item3.jl")
@safetestset "Vector-form SCCNonlinearProblem with FunctionWrappers" include("core_tests__item4.jl")
@safetestset "HomotopyProblem SCC block is continued (autodiff threaded)" include("core_tests__item5.jl")
@safetestset "AutoDespecialize SCC subproblems" include("core_tests__item6.jl")
@safetestset "Vector{Any} SCC container eltype is preserved" include("core_tests__item7.jl")
@safetestset "SteadyStateProblem SCC lowering and linear-block kwargs" include("core_tests__item8.jl")
