@safetestset "Interval Nonlinear Problems" include("rootfind_tests__item1.jl")
@safetestset "Tolerance Tests Interval Methods" include("rootfind_tests__item2.jl")
@safetestset "Zero-Tolerance Tests Interval Methods" include("rootfind_tests__item3.jl")
@safetestset "ForwardDiff with Duals in tspan" include("rootfind_tests__item4.jl")
@safetestset "ModAB non-shrinking iteration" include("rootfind_tests__item5.jl")
@safetestset "Flipped Signs and Reversed Tspan" include("rootfind_tests__item6.jl")
@safetestset "Problem kwargs forwarded to solvers" include("rootfind_tests__item7.jl")
@safetestset "Function evaluated only inside the bracket" include("rootfind_tests__item8.jl")
@safetestset "ModAB robustness to overflow, NaN and mixed types" include("rootfind_tests__item9.jl")
@safetestset "Brent: one evaluation per point, and the minimum step" include("rootfind_tests__item10.jl")
@safetestset "Tomov's counterexample" include("rootfind_tests__item11.jl")
