@safetestset "Correctness vs the monolithic twin" include("core_tests__item1.jl")
@safetestset "Convergence order and the Schur corrector" include("core_tests__item2.jl")
@safetestset "Jacobian reuse, assembly points and line search" include("core_tests__item3.jl")
@safetestset "Postcondition and rejected configurations" include("core_tests__item4.jl")
@safetestset "Local tolerance schedules" include("core_tests__item5.jl")
@safetestset "Trial/commit determinism and the local ensemble" include("core_tests__item6.jl")
@safetestset "Linear preconditioning and linear forcing" include("core_tests__item7.jl")
@safetestset "Failure semantics, reinit! and counters" include("core_tests__item8.jl")
@safetestset "Full-space arm (Variant A)" include("core_tests__item9.jl")
