@safetestset "DFSane" include("core_tests__item1.jl")
@safetestset "DFSane Iterator Interface" include("core_tests__item2.jl")
@safetestset "DFSane NewtonRaphson Fails" include("core_tests__item3.jl")
@safetestset "DFSane: Kwargs" include("core_tests__item4.jl")
@safetestset "DFSane Termination Conditions" include("core_tests__item5.jl")
