@safetestset "Scalar Jacobians: Issue #451" include("misc_tests__item1.jl")
@safetestset "Dual of BigFloat: Issue #512" include("misc_tests__item2.jl")
@safetestset "TrustRegion reinit! resets trust_region" include("misc_tests__item3.jl")
@safetestset "Line search uses forward-mode autodiff: Issue #837" include("misc_tests__item4.jl")
@safetestset "Default NLLS polyalg is forward-mode only: Issue #837" include("misc_tests__item5.jl")
@safetestset "Eisenstat-Walker forcing reinit! resets forcing state" include("misc_tests__item6.jl")
@safetestset "Deferred residual evaluation" include("misc_tests__item7.jl")
@safetestset "No redundant terminal residual evaluation" include("misc_tests__item8.jl")
@safetestset "Gradient stationarity termination (#1149)" include("misc_tests__item9.jl")
