@safetestset "Scalar Jacobians: Issue #451" include("misc_tests__item1.jl")
@safetestset "Dual of BigFloat: Issue #512" include("misc_tests__item2.jl")
@safetestset "TrustRegion reinit! resets trust_region" include("misc_tests__item3.jl")
@safetestset "Line search uses forward-mode autodiff: Issue #837" include("misc_tests__item4.jl")
@safetestset "Default NLLS polyalg is forward-mode only: Issue #837" include("misc_tests__item5.jl")
