@safetestset "Eisenstadt-Walker Newton-Krylov" include("rootfind_tests__item1.jl")
@safetestset "NewtonRaphson" include("rootfind_tests__item2.jl")
@safetestset "NewtonRaphson: Iterator Interface" include("rootfind_tests__item3.jl")
@safetestset "NewtonRaphson Termination Conditions" include("rootfind_tests__item4.jl")
@safetestset "PseudoTransient" include("rootfind_tests__item5.jl")
@safetestset "PseudoTransient: Iterator Interface" include("rootfind_tests__item6.jl")
@safetestset "PseudoTransient Termination Conditions" include("rootfind_tests__item7.jl")
@safetestset "TrustRegion" include("rootfind_tests__item8.jl")
@safetestset "TrustRegion: Iterator Interface" include("rootfind_tests__item9.jl")
@safetestset "TrustRegion NewtonRaphson Fails" include("rootfind_tests__item10.jl")
@safetestset "TrustRegion: Kwargs" include("rootfind_tests__item11.jl")
@safetestset "TrustRegion OOP / IIP Consistency" include("rootfind_tests__item12.jl")
@safetestset "TrustRegion Termination Conditions" include("rootfind_tests__item13.jl")
@safetestset "LevenbergMarquardt" include("rootfind_tests__item14.jl")
@safetestset "LevenbergMarquardt NewtonRaphson Fails" include("rootfind_tests__item15.jl")
@safetestset "LevenbergMarquardt: Iterator Interface" include("rootfind_tests__item16.jl")
@safetestset "LevenbergMarquardt Termination Conditions" include("rootfind_tests__item17.jl")
@safetestset "LevenbergMarquardt: Kwargs" include("rootfind_tests__item18.jl")
@safetestset "Simple Sparse AutoDiff" include("rootfind_tests__item19.jl")
@safetestset "Custom JVP" include("rootfind_tests__item20.jl")
