name: CI (BracketingNonlinearSolve)

on:
  pull_request:
    paths:
      - "lib/BracketingNonlinearSolve/**"
      - ".github/workflows/CI_BracketingNonlinearSolve.yml"
      - "lib/NonlinearSolveBase/**"
      - "lib/SciMLJacobianOperators/**"
  push:
    branches:
      - master

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.10"
          - "1"
        os:
          - ubuntu-latest
          - macos-latest
    uses: LuxDL/Lux.jl/.github/workflows/CommonCI.yml@main
    with:
      julia_version: ${{ matrix.version }}
      os: ${{ matrix.os }}
      project: "lib/BracketingNonlinearSolve"
      local_dependencies: "lib/NonlinearSolveBase,lib/SciMLJacobianOperators"

  downgrade:
    uses: LuxDL/Lux.jl/.github/workflows/CommonCI.yml@main
    with:
      julia_version: "1.11"
      project: "lib/BracketingNonlinearSolve"
      downgrade_testing: true
