name: CI (NonlinearSolve)

on:
  pull_request:
    paths:
      - "src/**"
      - "ext/**"
      - "test/**"
      - "Project.toml"
      - ".github/workflows/CI_NonlinearSolve.yml"
      - "lib/SciMLJacobianOperators/**"
      - "lib/BracketingNonlinearSolve/**"
      - "lib/NonlinearSolveBase/**"
      - "lib/SimpleNonlinearSolve/**"
      - "lib/NonlinearSolveFirstOrder/**"
      - "lib/NonlinearSolveSpectralMethods/**"
      - "lib/NonlinearSolveQuasiNewton/**"
  push:
    branches:
      - master

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  tests:
    uses: "SciML/.github/.github/workflows/grouped-tests.yml@v1"
    with:
      group-env-name: NONLINEARSOLVE_TEST_GROUP
      check-bounds: auto
    secrets: "inherit"
