name: IntegrationTest

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceI, upstream_subdirs: "."}
          - {user: SciML, repo: ModelingToolkit.jl, group: InterfaceII, upstream_subdirs: "."}
          - {user: SciML, repo: ModelingToolkit.jl, group: Initialization, upstream_subdirs: "."}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Interface, upstream_subdirs: "."}
          - {user: SciML, repo: OrdinaryDiffEq.jl, group: Regression, upstream_subdirs: "."}
          - {user: SciML, repo: BoundaryValueDiffEq.jl, group: All, upstream_subdirs: "lib/NonlinearSolveBase,lib/SciMLJacobianOperators,lib/NonlinearSolveFirstOrder"}
          - {user: SciML, repo: DiffEqCallbacks.jl, group: Core, upstream_subdirs: "."}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      upstream-subdirs: "${{ matrix.package.upstream_subdirs }}"
      group: "${{ matrix.package.group }}"
      julia-version: "1"
    secrets: "inherit"
